name: CI

on: [push]

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Install Pester
      shell: pwsh
      run: Invoke-Pester test -EnableExit
